### ISSUE TITLE
Google Play Services - New Structure (rev. 30)

### ISSUE THREAD

**Issue by DarioFT** [SempaiGames/extension-googleplaygames#24]
As it's discussed in this topic at [StackOverflow](http://stackoverflow.com/questions/37310684/missing-sdk-extras-google-google-play-services-libproject-folder-after-updat/) it seems that _google-play-services library_ has been substantially modified. As we've been able to test, this new changes definitely broke the extension and the only workaround for the problem is to still use old revisions (rev. 29 and older), due the impossibility of access to _google_play_services/libproject_.

Further updates for this extension may require to implement some big changes to access the classes and methods packed in different _aar_ files. Is there any other possible workaround or should we stay with older revisions until future updates of this library?

**Comment by fbricker** [comment]
Hi, If it's true that google refactored google_play_services library, then extension-googleplayservices-lib will require some work.
Meanwhile, take a look here: https://github.com/SempaiGames/extension-googleplayservices-lib/issues/3

I don't want to do anything on the extension until google officially updates it's documentation (since as today, google official documentation still says you shoud use the library inside <android-sdk>/extras/google/google_play_services/libproject/google-play-services_lib/, so there's a small chance that they'll fix this on next release).

![captura de pantalla 2016-05-31 a las 3 55 03 p m](https://cloud.githubusercontent.com/assets/1865352/15686780/3258e09c-2748-11e6-8d2b-70d52f754674.png)
